#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

# http://www.smddzcy.com/2016/01/installing-configuring-php7-zts-on-os-x/
(php -v | grep 'PHP 7.1') || brew install php71 --with-thread-safety --with-phpdbg

which composer || brew install composer

composer install
composer update
